### ISSUE TITLE
Not Indexing

### ISSUE THREAD

**Issue by matthewscalf** [magemojo/m2-ce-cron#102]
I installed the plugin and I "think" it's working but it does not seem to be running all the jobs. Like indexing does not seem to trigger at all. I see some are running for sure but it's either backlogged or something. Should I truncate the table and let it start fresh. I know when I installed it I had the cpu setting too low so it actually wasn't triggering.

**Comment by gnuzealot** [comment]
If they aren't running they would show as being queued and then missed in the report. If that's happening then you probably have other issues with jobs running really long and blocking the execution of other.

**Comment by gnuzealot** [comment]
No additional updates on the issue, assuming missed due to overrunning or too many concurrent processes.
