### ISSUE TITLE
Magento 2.4.5 p1 / Php 8.1 Compatibilty 

### ISSUE THREAD

**Issue by gopinathchan** [magemojo/m2-ce-cron#126]
Module is not compatible with latest version of php

We got error like below.

vendor/magemojo/m2-ce-cron/Model/Schedule.php 970
Deprecated Functionality: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated

vendor/magemojo/m2-ce-cron/view/adminhtml/templates/reports.phtml on line 54
Deprecated Functionality: strtotime(): Passing null to parameter #1 ($datetime) of type string is deprecated

**Comment by gnuzealot** [comment]
Fixed in 1.4.3
