### ISSUE TITLE
Error with extension on Magento 2.1

### ISSUE THREAD

**Issue by Ctucker9233** [magemojo/m2-ce-cron#13]
I'm trying to use your extension on Magento 2.1 and when I run bin/magento setup:di:compile I get the following error

 Incorrect dependency in class MageMojo\Cron\Controller\Adminhtml\Settings\Index in /home/tuckersf/public_html/app/code/MageMojo/Cron/Controller/Adminhtml/Settings/Index.php
\Magento\Framework\Message\ManagerInterface already exists in context object
Total Errors Count: 1

Please provide a fix as soon as possible.

**Comment by gnuzealot** [comment]
@Ctucker9233  Try clearing clearing the folder generated/* first before compiling.

**Comment by Ctucker9233** [comment]
@gnuzealot I ran rm -rf var/di var/generation var/cache/* var/page_cache/* pub/static/frontend/* before running the upgrade and compile commands

**Comment by gnuzealot** [comment]
@Ctucker9233 what was the full version number? I'll try to reproduce it here.

**Comment by Ctucker9233** [comment]
Version of Magento is 2.1.11. Is that what you meant by full version number?

**Comment by gnuzealot** [comment]
@Ctucker9233 Please try it now, should be fixed with https://github.com/magemojo/m2-ce-cron/commit/5be6233b8df8432d6d4bc6e73f4c18112b85e617

**Comment by Ctucker9233** [comment]
It works perfectly now. Thank you.

**Comment by gnuzealot** [comment]
Excellent, closing the issue.
