### ISSUE TITLE
cron table overload

### ISSUE THREAD

**Issue by brigittevelten** [magemojo/m2-ce-cron#17]
Thank you for your module, I installed it, but my cron schedule table has more than 20000 pending jobs.
I know your module prevents that several cron jobs run at the same time, but how can I prevent that so many cron jobs are created.
Looking forward to hearing from you
Brigitte

**Comment by gnuzealot** [comment]
When did you install it? I found instances where if old data is in the from table it will create extra entries but that was fixed this morning.

**Comment by brigittevelten** [comment]
Dear Martin,

Thank you so much for your answer, I downloaded the files on march 19th  and installed it yesterday.

I had old data in the cron schedule tab. I deleted all entries this afternoon and now I have again 5000 entries pending.

Should I reinstall the new version, you corrected today ?

Kind regards

Brigitte

 

 

De : Martin Pachol [mailto:notifications@github.com] 
Envoyé : March-21-18 5:01 PM
À : magemojo/m2-ce-cron
Cc : brigittevelten; Author
Objet : Re: [magemojo/m2-ce-cron] cron table overload (#17)

 

When did you install it? I found instances where if old data is in the from table it will create extra entries but that was fixed this morning.

**Comment by gnuzealot** [comment]
Yes, please try the latest, that will force everything to UTC time and should prevent that. The new version also has cron reporting in the admin.

**Comment by brigittevelten** [comment]
Dear Martin,

Thank you so much, I really appreciate your help.

 

Brigitte

 

De : Martin Pachol [mailto:notifications@github.com] 
Envoyé : March-21-18 10:52 PM
À : magemojo/m2-ce-cron
Cc : brigittevelten; Author
Objet : Re: [magemojo/m2-ce-cron] cron table overload (#17)

 

Yes, please try the latest, that will force everything to UTC time and should prevent that. The new version also has cron reporting in the admin.

**Comment by gnuzealot** [comment]
No problem, going to close this issue out.
