### ISSUE TITLE
Template Hints in Sales Order Email

### ISSUE THREAD

**Issue by cbend** [magemojo/m2-ce-cron#21]
With the module enabled, order emails are displaying template hints. It is not happening with the module disabled in app/etc/config.php.

![image](https://user-images.githubusercontent.com/25639152/38104472-3bfdb858-3357-11e8-82a1-e49b4ca23e47.png)

Spec:
1. Magento version 2.2.2
2. MageMojo_Cron version 1.0.1

Steps to reproduce:
1. Place an order
2. Or use "Send Email" in the admin

**Comment by gnuzealot** [comment]
I'm not able to repeat the issue on a default 2.2.2 store. Maybe a conflict with another module or some setting. Would you be able to send me a list of all your installed modules and a dump of the core_config_data table?

**Comment by rhoerr** [comment]
This only affects order confirmation emails, and only when those emails are set to send asynchronously (by cron).

1. Verify cron is running
2. Set **Admin > Stores > Configuration > Sales > Sales Emails > General Settings > Asynchronous sending** to Enable (default Disable)

Then you should be able to reproduce by placing an order or resending an existing order email.

**Comment by gnuzealot** [comment]
I'm able to reproduce the problem now. Definitely some core magento bug where it's including that stuff based on how the method is executed. Still trying to find a workaround for it.

**Comment by gnuzealot** [comment]
Fixed in https://github.com/magemojo/m2-ce-cron/commit/254e4031ffa71efb773c4bc620e7c510cb2f01ca
