### ISSUE TITLE
Strange output in magento.cron.log

### ISSUE THREAD

**Issue by Ctucker9233** [magemojo/m2-ce-cron#22]
When cron runs on Magento 2.1.11 when using your extension, the mageno.cron.log shows this output multiple times "cat: /proc/cpuinfo: No such file or directory". Is this an error and if so, how can it be fixed?

**Comment by gnuzealot** [comment]
What operating system are you on? That function is trying to get the number of cpu cores available and that file should be on any linux based system.

**Comment by gnuzealot** [comment]
Closing due to no response.
