### ISSUE TITLE
Issue when also using Wyomind cronscheduler

### ISSUE THREAD

**Issue by ctadlock** [magemojo/m2-ce-cron#23]
https://github.com/wyomind/cronscheduler

`cronscheduler_heartbeat`
```PHP Fatal error: Uncaught Error: Call to a member function setMessages() on null in /data/Store4/src/web/app/code/Wyomind/CronScheduler/Cron/HeartBeat.php:24 Stack trace: #0 Command line code(1): Wyomind\CronScheduler\Cron\HeartBeat->heartbeat() #1 {main} thrown in /data/Store4/src/web/app/code/Wyomind/CronScheduler/Cron/HeartBeat.php on line 24```

**Comment by ctadlock** [comment]
![image](https://user-images.githubusercontent.com/1539397/38471731-26498ea8-3b2a-11e8-8f37-dd2ea7a98eb6.png)

**Comment by ctadlock** [comment]
This error looks to be happening to all cron tasks that have a parameter of `\Magento\Cron\Model\Schedule $schedule`. Im now seeing the error happen on other cron tasks.

**Comment by ctadlock** [comment]
According to (https://github.com/magento/magento2/issues/7005) it looks like parameters are not supposed to be passed to the method the cron task executes, so this is really a bug in the Wyomind code. Ive contacted them to resolve it.

**Comment by gnuzealot** [comment]
@ctadlock  OK, thanks for looking into that so thoroughly. I'll close this out for now. If Wyomind doesn't resolve it we can look for a workaround.

**Comment by ctadlock** [comment]
Looks like it might not be this easy.. now a couple more extensions are having similar issues; some in Magento code and another in MageWorx Ultimate SEO. Its not clear to me what the coding convention is. The Magento issues above, @DaimPiek claims that the method should have no parameters; but I cant find any other documentation to support it. The [example](http://devdocs.magento.com/guides/v2.2/config-guide/cron/custom-cron-tut.html) shows no parameters. Given that there are Magento core con tasks that dont follow this, I think it needs to be dealt with in this extension.

@gnuzealot Im not sure where it is in this code, but wherever its actually executing the function for the cron task, you need to pass in an instance of the `Schedule` class. Ill leave that to you.

![image](https://user-images.githubusercontent.com/1539397/38474167-fc3c8fb8-3b4f-11e8-95ff-878d181bd80e.png)

**Comment by ctadlock** [comment]
Looking at the Magento2 code, it does pass in the `Schedule` class.

https://github.com/magento/magento2/blob/2.2/app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php#L292

![image](https://user-images.githubusercontent.com/1539397/38474430-9a6fcfd0-3b53-11e8-9ada-38c6d3f830b2.png)

**Comment by gnuzealot** [comment]
Damn that's inconsistent. None of the standard magento cron methods accept that parameter. Not clear in their code how they can be passing an unexpected argument and not have it error either. There must be some magic that the call_user_func_array() does.

Anyway, should be able to get this condition working tomorrow.

**Comment by ctadlock** [comment]
A couple Magento cron tasks do. For example, `currency_rates_update`: 
https://github.com/magento/magento2/blob/2.2/app/code/Magento/Directory/etc/crontab.xml#L10
https://github.com/magento/magento2/blob/2.2/app/code/Magento/Directory/Model/Observer.php#L90

What I cant figure out is how this didn't break for everyone else?

**Comment by ctadlock** [comment]
I deployed 1.1.2. It seems there is still an issue where `$schedule` is `null`. I need to wait a bit more time to verify the other cron jobs. You might not have seen this error since most (if not all) of the Magento cron jobs (`currency_rates_update`) dont actually use the `$schedule` parameter, so they dont care if its `null`. This Wyomind `cronscheduler_heartbeat` cron job does use it, and is executed every minute so its a good test case. See above for their code.

![image](https://user-images.githubusercontent.com/1539397/38513644-b5bb6b56-3be3-11e8-8246-ba7684b06417.png)

**Comment by gnuzealot** [comment]
I installed the Wyomind module and the cronscheduler_heartbeat task ran successfully.  Did you stop the parent cron process, or disable / reenable to restart the process with the new code?

**Comment by ctadlock** [comment]
I rebooted the server and it all worked. Im not sure I understand the parent process. I had restarted apache several times and it didn't resolve this. Besides rebooting the server, what is the process for restarting cron?

**Comment by gnuzealot** [comment]
The code runs as a continual php process that loops and picks up new jobs and schedules accordingly. If you run the cron process again it will just check to see if the service is alive and it not it will run. To restart it you can just set the process to disabled for a bit in the admin and then reenable it. This prevents overruns as the process tracks cron execution by pid.

**Comment by gnuzealot** [comment]
There should be, it should only be running the pid listed in var/cron/cron.pid

**Comment by ctadlock** [comment]
I rebooted again, and now there is only one `php` process that matches the `cron.pid`. Not sure where the other process came from.

I think everything is good now, will let this run for a day and will report any issue. I think you can close. Thanks for the fast response.

**Comment by ctadlock** [comment]
Working perfectly. The error logging is very nice as its already helped me to find some issues that were previously hidden in other parts of the store.
