### ISSUE TITLE
Large number of files in var/cron/

### ISSUE THREAD

**Issue by ctadlock** [magemojo/m2-ce-cron#25]
I left the my store running untouched for 2 weeks; there were 335,919 files in `var/cron/`. Configured for 3 days of history retention.

![image](https://user-images.githubusercontent.com/1539397/39383760-50dfdccc-4a1f-11e8-8b0e-0d2738a553e2.png)

![image](https://user-images.githubusercontent.com/1539397/39383985-1bcff656-4a20-11e8-9be1-a7d6142b4f4b.png)

**Comment by gnuzealot** [comment]
Those should be cleaned by the cleanup process that truncates the history. Most are not needed, just for debugging. I'll check into it later today.

**Comment by gnuzealot** [comment]
OK, this is resolved in https://github.com/magemojo/m2-ce-cron/commit/e2db48ff0459ba78e7d44a8a5f623ecd576273e0

scheduleid files will be removed after crons execute now. Any orphaned files will be removed after the history retention period.

**Comment by ctadlock** [comment]
Ive confirmed this has been resolved.
