### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by koralgolek** [magemojo/m2-ce-cron#26]
Magento 2.2.3
After bin/magento setup:upgrade I get:

<code>
Updating modules:
Class MageMojo\Cron\Model\Schedule does not exist

                                                     
  [ReflectionException]                              
  Class MageMojo\Cron\Model\Schedule does not exist  
                                                     

                                                     
  [ReflectionException]                              
  Class MageMojo\Cron\Model\Schedule does not exist  
                                                     

                                                                       
  [ParseError]                                                         
  syntax error, unexpected 'running' (T_STRING), expecting ',' or ')'  
                                                                       </code>

**Comment by gnuzealot** [comment]
Had a syntax error in that file. Fixed in https://github.com/magemojo/m2-ce-cron/commit/2e5074707f207dc16d74073df0c484dbebe01cf0

Please download the latest version.
