### ISSUE TITLE
Notice: Undefined index: schedule_id 

### ISSUE THREAD

**Issue by JesKingDev** [magemojo/m2-ce-cron#30]
1. What version of the Magento are you using (the full version ex. 2.1.11)?
Magento Open Source 2.2.0

2. What did you do?
I am running the m2-ce-cron extension in an AWS ElasticBeanstalk environment, where the Magento crons are executed only if the server is currently the "leader" server in the cluster. This allows for maintenance, downtime, and rolling updates while keeping a continuous cron execution.

3. What did you expect to see?
When the "leader" switches from one server to another, the server should gracefully pick up and resume executing the cron jobs. My expectation is that the extension handles different server instances executing crons or provides a way to load balance/distribute the executions. The extension should take into account the execution host.

4. What did you see instead?
When the "leader" role is granted to a different server, I receive dozens of the following messages via emails from Cron Daemon:
```

[Exception]                                                                                                     
Notice: Undefined index: schedule_id in /var/app/current/app/code/MageMojo/Cron/Model/Schedule.php on line 442 

cron:run [--group GROUP] [--bootstrap BOOTSTRAP]
```

**Comment by gnuzealot** [comment]
@JesKingDev  Are the nodes using separate filesystems for /var?

**Comment by oroskodias** [comment]
Experiencing the same issue. Magento Open Source 2.2.2 and 2.2.3

**Comment by gnuzealot** [comment]
@oroskodias what line number was reported, there have been updates since this was reported and that variable is used multiple times in that file.

**Comment by oroskodias** [comment]
@gnuzealot I apologize, our version is not up to date. My version is 1.1.5. Now I see it was fixed

**Comment by gnuzealot** [comment]
Excellent, I'm going to close this out.

**Comment by oroskodias** [comment]
It still exists in the latest 1.2.0 version. Error is:

`[Exception]                                                                                                                     
  Notice: Undefined index: schedule_id in /srv/releases/*****/vendor/magemojo/m2-ce-cron/Model/Schedule.php on line 478  `

I'm working on a fix and I will submit pull request
