### ISSUE TITLE
Error while removing non-existent PID file

### ISSUE THREAD

**Issue by oroskodias** [magemojo/m2-ce-cron#34]
While running `/usr/local/bin/php /srv/current/bin/magento cron:run` we're getting this error which prevents cron from running. Exception is that:

`[Exception]                                                                                                                                        
  Warning: unlink(/srv/releases/20180523123705/var/cron/schedule.6381): No such file or directory in /srv/releases/20180523123705/vendor/magemojo/m2-ce-cron/Model/Schedule.php on line 98`

Also extension is not following default Magento code guidelines and using not safe methods to check file existence, getting file contents and saving file contents. I already fixed it in our project and I also can push these changes and create pull request.

**Comment by gnuzealot** [comment]
@oroskodias thank you, the pull request has been merged

**Comment by oroskodias** [comment]
@gnuzealot you closed wrong issue. I still didn't finished PR for that issue.

**Comment by gnuzealot** [comment]
Reopened

**Comment by gnuzealot** [comment]
fixed in #36
