### ISSUE TITLE
Too many errors and 'imagick' warning.

### ISSUE THREAD

**Issue by anytime1106** [magemojo/m2-ce-cron#37]
Hi! I 'm using your m2-ce-cron module.
I installed this module a couple of days ago, and today I got some errors at cron report.
![cronjob](https://user-images.githubusercontent.com/19610902/41489390-e9367bb0-70bd-11e8-84c3-5ca7e4c91c48.jpg)

The errors are below image.
![cronjoberror](https://user-images.githubusercontent.com/19610902/41489371-d6cc003a-70bd-11e8-8fcb-c862ae55e6e2.jpg)

I'm wondering if it is working properly and if this issue affect other settings.

How can I fix this issue?

**Comment by gnuzealot** [comment]
@anytime1106 This looks like an issue with your php runtime environment. The extension doesn't use imagemagick at all. You'll probably see the same warnings if you run php -v from the command line as well. Your web host would need to look into that. Even though they are showing as errors the jobs are probably still running. The code is just expecting that the command should not have any output.

**Comment by anytime1106** [comment]
@gnuzealot  After installed your module, our cron job didn't work properly.... 
First of all, indexer didn't reindex.
So we removed your module, we found the error in 'cron_schedule' table below.
It seems that the cron job is working properly because the scheduler created 60 rows every hours and executed every minuets. But while it is executing, the same errors occurred on and on.

![cronerror](https://user-images.githubusercontent.com/19610902/41562510-dc20311e-731a-11e8-9f6b-4c32c7e82491.jpg)


Our hosting company support team said the modules/extension I installed about cron job modified something code associated with cron. 

Do you know why it is occurred??

Thanks!

**Comment by gnuzealot** [comment]
@anytime1106 if the module is uninstalled then it's not going to effect the built in cron functionality of M2. I'm not able to repeat these problems on this end so I can do little to debug your issue. If you could give me access to check it on your server I'd be more than happy though. A dev environment would be fine for that as long as it is repeatable there.

**Comment by gnuzealot** [comment]
Closing, not repeatable and cannot get access to debug,
