### ISSUE TITLE
Incorrect timestamp for 'finished_at'

### ISSUE THREAD

**Issue by dccampbell** [magemojo/m2-ce-cron#38]
After enabling this module, I noticed that all entries in `cron_schedule` now have matching values for `executed_at` and `finished_at`. It seems `finished_at` is getting set immediately, even for jobs that continue running for a long time.

Disabling the module I immediately see the two values diverge, and after enabling it again they are 100% the same.

Magento v2.2.4

**Comment by gnuzealot** [comment]
Confirmed this issue, will be fixed in the next release
