### ISSUE TITLE
Warning: exec(): Unable to fork [cat /proc/cpuinfo | grep processor | wc -l]

### ISSUE THREAD

**Issue by JesKingDev** [magemojo/m2-ce-cron#39]
I began receiving this error in my environment today.

**Environment Details**
Magento Open Source 2.2.2
AWS EC2 c4.large / Ubuntu
PHP 7.0

**Cron Error**
[Exception] 
Warning: exec(): Unable to fork [cat /proc/cpuinfo | grep processor | wc -l] in /var/app/current/vendor/magemojo/m2-ce-cron/Model/Schedule.php on line 316 

cron:run [--group GROUP] [--bootstrap BOOTSTRAP]

**Comment by gnuzealot** [comment]
@JesKingDev  That error could have several different causes as outlined in this thread.

https://stackoverflow.com/questions/20648949/php-warning-exec-unable-to-fork

However it's most likely that that the user that php is running as doesn't have access to read that file, which contains the information about the number of processors. The extension uses that info to determine the system load average and suspend cron function if it's too high. It won't interfere with the crons running though as it's just going to always detect the load average as 0 in this case.

We'll add in functionality to detect this case and disable the load average checking in the next release.

**Comment by gnuzealot** [comment]
Added check in https://github.com/magemojo/m2-ce-cron/commit/54954b8b6f248c6b3ab461fcdb1b14059eee7bdc
