### ISSUE TITLE
check its working

### ISSUE THREAD

**Issue by mattyl** [magemojo/m2-ce-cron#41]
Silly question - but everything seems correctly installed, the log file says 
Healthchecking Cron Service
every couple of minutes
the folders are create - but the schedule folder is empty
in admin the table is empty
the cron table is empty
So how can i check its working as expected? Any ideas?

**Comment by mattyl** [comment]
Manually running php bin/magento cron:run seems to have got it going 
- although the crons are there working
- still concerned something isn't quite right and i am missing something

**Comment by JesKingDev** [comment]
@mattyl Did you create the Magento crontab as per https://devdocs.magento.com/guides/v2.2/config-guide/cli/config-cli-subcommands-cron.html?

**Comment by mattyl** [comment]
yes! I installed this because of the problem with crons getting stuck and crashing the server - but the crons were running fine
in case i am being too clever and missing sometihng obvious

* * * * * /opt/cpanel/ea-php71/root/usr/bin/php /home/keene/public_html/bin/magento cron:run 2>&1 | grep -v "Ran jobs by schedule" >> /home/keene/public_html/var/log/magento.cron.log
* * * * * /opt/cpanel/ea-php71/root/usr/bin/php /home/keene/public_html/update/cron.php >> /home/keene/public_html/var/log/update.cron.log
* * * * * /opt/cpanel/ea-php71/root/usr/bin/php /home/keene/public_html/bin/magento setup:cron:run >> /home/keene/public_html/var/log/setup.cron.log

is my crontab

**Comment by mattyl** [comment]
I also changed php to /opt/cpanel/ea-php71/root/usr/bin/php in the settings in case that was the issue

**Comment by mattyl** [comment]
is this process meant to run and run? when i did it manually everything worked, but my CSF firewall was moaning about a never ending process - when i killed that process it never started again

**Comment by gnuzealot** [comment]
Yes, it is running as a service so it will run until killed or the heat death of the universe.

**Comment by mattyl** [comment]
Ah - but is there way of initiating it without running manually php bin/magento cron:run

i think this would be useful in the readme notes, i am running a standard cpanel server with the CSF firewall - it sends me messages when a process lasts more than x seconds

unless i manually ignore it in the pignore.txt

which i will do now!

But you can see how worrisome that would be if you didn’t know.

**Comment by gnuzealot** [comment]
Just running in a cron the way you have should be working. Might need to check your /var/cron logs to see if there is some other error.

**Comment by mattyl** [comment]
Thanks for that, it seems to be running ok, i removed my old crons and used the magento script to reinstall - they were identical but now it has the 
#~ MAGENTO START
#~ MAGENTO END
comments in the crontab
could this be the issue? For me it seems ot be working and I have whitelisted the 3 processes - but for those following - if the comments are necessary for some reason it would be good to know! thanks for your help

**Comment by gnuzealot** [comment]
I can't think how that would make any difference to it. Comments in the crontab wouldn't effect the code running from it. Maybe some cpanel peculiarity.

**Comment by mattyl** [comment]
I am really sorry there is an issue somewhere here. The service stopped (due to an error) over night - it doesnt restart
the cron returns
Healthchecking Cron Service

But it only a manual intervention does it also return
Starting Service

I appreciate there must be something in my setup that is stopping the service starting, any idea how i can test this?

**Comment by gnuzealot** [comment]
Is there anything in the system cron log that is saying why it isn't starting?

**Comment by mattyl** [comment]
No, sorry, that’s why I was raising it as an issue, have checked all logs
The cron is running and triggering the health check notice, but it’s not starting the service .

**Comment by mattyl** [comment]
Hi, absolutely nothing

but its failing every day at 1.00am

  [Exception]                                                                                                           
  Notice: Undefined index: method in /home/keene/public_html/vendor/magemojo/m2-ce-cron/Model/Schedule.php on line 304  

and because it doesn’t auto initialise, i have to manually restart every day

please where in the code is it being started so i can see if i can fix it, to see if its a specific or systematic issue

**Comment by gnuzealot** [comment]
Looks like it's failing due to there being a misconfigured job in the cron schedule. Basically there's a job, but there's no method defined for it that tries to run at 1am, I'll add an exception and catch an log that error in the next release. For why the cron isn't starting though I'd need to look on the system itself. There must be something about the environment that isn't allowing execution.

**Comment by mattyl** [comment]
yes i put in that and it allowed the cron to start, this site has m2e disabled

it very strange why

/opt/cpanel/ea-php71/root/usr/bin/php /home/xxx/public_html/bin/magento cron:run

works to initialise the service, but

/opt/cpanel/ea-php71/root/usr/bin/php /home/xxx/public_html/bin/magento cron:run 2>&1 | grep -v "Ran jobs by schedule" >> /home/xxx/public_html/var/log/magento.cron.log

doesn’t

I am sure it might be something about the environment, but as its an out of the box cpanel with csf firewall, i am sure its something that will interest others.

If i can do anything please let me know, as this looks a great solution to cron problem on m2

**Comment by mattyl** [comment]
Ok i have managed to back track this issue, almost - the cron.pid in my case is ALWAYS - 3
and not the actual process id
there is always a process id 3, so the plugin thinks its running when it isnt
my process 3 is a root process [ksoftirqd/0]
any ideas why getmypid is not returning the required process id?

**Comment by gnuzealot** [comment]
Are the permissions on the file incorrect so it is unable to write a new id to it? I don't see how it could pick up the pid for ksoftirqd, that's a process that deals with hardware IRQ's.

**Comment by mattyl** [comment]
nope they look fine, i have deleted the file many times to test, every time it comes up 3!

I even put in a line to write to a txt file just in case and check i was at the right place - again 3!

it comes from getmypid function, so my setup has to have something causing that to give an unhelpful number

I’ll play further tomorrow

**Comment by mattyl** [comment]
In my logs (using custom logging & a try/catch) i found the problematic cron

Array
(
    [schedule] => 0 0 * * *
    [name] => log_clean
)

this looks like a normal cron to me - but note no method. Our site was migrated from m1.

**Comment by gnuzealot** [comment]
Were you able to get that working or determine why it was always pulling pid 3?

**Comment by mattyl** [comment]
Sadly I couldn’t find time to dedicate to it, moving the site to a different server environment solved the issue

**Comment by gnuzealot** [comment]
OK, we'll chalk this up to being another reason to dislike cpanel. I'll close this out for now, please reopen if you find anything else.
