### ISSUE TITLE
Undefined index: in vendor/magemojo/m2-ce-cron/Model/Schedule.php on line 298

### ISSUE THREAD

**Issue by ctadlock** [magemojo/m2-ce-cron#46]
Magento 2.2.5
Extension: 1.2.4
PHP 7.1
Apache

![image](https://user-images.githubusercontent.com/1539397/43558911-8be8a46a-95c0-11e8-85fc-945c7cda62c0.png)

**Comment by tcurilla** [comment]
replace
Model/Schedule.php on line 421
`while ($this->canRunJobs($jobcount, $pending)) {`
` while (count($pending) && $this->canRunJobs($jobcount, $pending)) {`
