### ISSUE TITLE
magemojo all task pending

### ISSUE THREAD

**Issue by mpropl** [magemojo/m2-ce-cron#51]
MageMojo hangs and does not want to perform cron tasks all have pending status

**Comment by blmage** [comment]
Are you using the latest version? (1.2.5)
We had the same problem on a 1.2.3, and updating the module fixed it for us (certainly thanks to 5a32e4132b81454042bc8fac069e2781a4695979)

**Comment by gnuzealot** [comment]
Not able to reproduce, assuming it's fixed in latest version.
