### ISSUE TITLE
Job not scheduled at the top of the hour

### ISSUE THREAD

**Issue by lsrocha** [magemojo/m2-ce-cron#56]
A job, which should run once a day at 8 a.m, is not being scheduled on our production server. The cron service is creating new entries every hour at minute 59 (e.g. 06:59, 07:59 and go on) and is skipping jobs expected to run at the top of the hour (e.g. 08:00, 05:00). 

On our staging environment, the service runs every hour at minute 3 and those jobs are being scheduled perfectly. Testing on local, no abnormal behaviour was noticed.

Production environment (8:00 schedule skipped):
![image](https://user-images.githubusercontent.com/1460061/46432117-cfddc300-c723-11e8-8b38-8978df02cfb2.png)

Staging environment (17:00 schedule created):
![image](https://user-images.githubusercontent.com/1460061/46432846-a160e780-c725-11e8-9d5c-1928dc0c1edd.png)

Context:
- OS: Ubuntu 16.04.5 LTS
- PHP version: 7.0.32
- MySQL version: 5.6.27-log
- Magento version: 2.1.5
- Module version: 1.2.5-stable

**Comment by gnuzealot** [comment]
This appears to be coming down to the timing in which the schedule is being generated. The schedule is built out an hour ahead of time and under certain conditions it can miss the final minute. Schedule generation occurs based on the runtime of the parent cron process and in this case it is running at minute 59 causing it to miss top of the hour. I'm adjusting the schedule generation timing so it should get that final minute in the next release.

**Comment by gnuzealot** [comment]
fixed in https://github.com/magemojo/m2-ce-cron/commit/c68b66ffbb82f596c522b84f5453eb0d539c0009
