### ISSUE TITLE
What does CE stand for?

### ISSUE THREAD

**Issue by schmengler** [magemojo/m2-ce-cron#58]
Is it "Commerce Edition", "Community Edition", "Cloud Edition" or something else?

The question may sound stupid, but I don't find specific requirements and try to figure out if the module makes sense for Magento Commerce 2.2

**Comment by gnuzealot** [comment]
It is for community edition, but it also works for enterprise and has been tested there.

**Comment by schmengler** [comment]
Perfect, thanks :+1:
