### ISSUE TITLE
Cannot load Zend OPcache - it was already loaded

### ISSUE THREAD

**Issue by hyquality** [magemojo/m2-ce-cron#59]
I just enabled your extension, but when I check the Cron Report I see the same error for all jobs:

Cannot load Zend OPcache - it was already loaded Error in argument 1, char 2: option not found r Usage: php-cgi [-q] [-h] [-s] [-v] [-i] [-f ] php-cgi [args...] -a Run interactively -b | Bind Path for external FASTCGI Server mode -C Do not chdir to the script's directory -c | Look for php.ini file in this directory -n No php.ini file will be used -d foo[=bar] Define INI entry foo with value 'bar' -e Generate extended information for debugger/profiler -f Parse . Implies `-q' -h This help -i PHP information -l Syntax check only (lint) -m Show compiled in modules -q Quiet-mode. Suppress HTTP Header output. -s Display colour syntax highlighted source. -v Version number -w Display source with stripped comments and whitespace. -z Load Zend extension . -T Measure execution time of script repeated times.

How do I fix this?

**Comment by gnuzealot** [comment]
This appears to be an issue in your php environment set up. It's probably running the jobs correctly, just sending this warning at the runtime. Do you get this message when you just run "php -v" from ssh?

**Comment by hyquality** [comment]
Nope, this is what I see:

ea-php-cli Copyright 2017 cPanel, Inc.
PHP 7.1.23 (cli) (built: Oct 30 2018 20:59:11) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.23, Copyright (c) 1999-2018, by Zend Technologies

**Comment by hyquality** [comment]
Also, my feed manager is saying that the last cron is older than 1 hour, so I don't think it's running...

**Comment by gnuzealot** [comment]
This seems to describe the same issue on cpanel. It's dependent on how php is invoked what configs it ends up using. It seems that it is basically trying to load the zend opcache in two different configs.

https://forums.cpanel.net/threads/cannot-load-zend-opcache.612123/
