### ISSUE TITLE
"Timezone ID '' is invalid" on Cron Reports page

### ISSUE THREAD

**Issue by schmengler** [magemojo/m2-ce-cron#60]
The following error is shown in developer mode, when I try to access the cron reports
```
Notice: date_default_timezone_set(): Timezone ID '' is invalid in /var/www/html/vendor/magemojo/m2-ce-cron/view/adminhtml/templates/reports.phtml on line 8
```

**Comment by schmengler** [comment]
I see there's already a PR for the config issue (#54), I'll see to create another one for the timezone

**Comment by gnuzealot** [comment]
OK, I'll do the testing on previous versions with the new method.

**Comment by ericvhileman** [comment]
@gnuzealot
