### ISSUE TITLE
Proposal: Add support for NewRelic transaction name

### ISSUE THREAD

**Issue by JesKingDev** [magemojo/m2-ce-cron#64]
For environments integrated with NewRelic, cron executions are reported as transaction name 'unknown'. This makes troubleshooting crons difficult.

Per https://docs.newrelic.com/docs/agents/php-agent/troubleshooting/transactions-named-indexphp-or-unknown, this can be overcome by calling the NewRelic API to name the transaction. 

I propose using this solution to pass the job name when starting the job through the stub.
`if (extension_loaded ('newrelic')) {  newrelic_name_transaction (<<job_code>>);}`

**Comment by JesKingDev** [comment]
Submitted PR https://github.com/magemojo/m2-ce-cron/pull/66. I've created a patch which can be applied in the interim until the PR is reviewed and merged.  The patch can be applied following the instructions in my repo (linked in my commits to this ticket). The patch has been applied in 2 of my environments and is working perfectly.

**Comment by ericvhileman** [comment]
Thank you @JesKingDev
