### ISSUE TITLE
Proposal: Improve database query performance through indexes

### ISSUE THREAD

**Issue by JesKingDev** [magemojo/m2-ce-cron#65]
NewRelic reports slow transaction performance for cron lookups. Recommend adding indexes on the fields used for filtering, sorting, and grouping in the MageMojo module.

Slow query trace
5:55 AM
643ms
Query
` SELECT cron_schedule.* FROM cron_schedule WHERE (status = ?) `

Table | Hint
cron_schedule | This table was retrieved with a full table scan, which is often quite bad for performance, unless you only retrieve a few rows.The table was retrieved with this index: No index was used in this part of the query.You can speed up this query by querying only fields that are within the index. Or you can create an index that includes every field in your query, including the primary key.Approximately 99670 rows of this table were scanned.

Slow query trace
5:55 AM
693ms

Query
`SELECT max(schedule_id) AS schedule_id, cron_schedule.job_code, count(*) AS job_count FROM cron_schedule WHERE (status = ?) AND (scheduled_at < ?) GROUP BY job_code`

Table | Hint
cron_schedule | This table was retrieved with an index scan, which is like a full table scan, except it only hits the index (not the actual table). This is usually not great for performance.The table was retrieved with this index: CRON_SCHEDULE_JOB_CODEYou can speed up this query by querying only fields that are within the index. Or you can create an index that includes every field in your query, including the primary key.Approximately 102041 rows of this table were scanned.

**Comment by gnuzealot** [comment]
This is a default magento table. Adding this in a module could potentially break an upgrade in the future if they modify this table structure.
