### ISSUE TITLE
"Generate Schedules Every" setting used incorrectly.

### ISSUE THREAD

**Issue by aligent-lturner** [magemojo/m2-ce-cron#67]
In #50 the issue was raised that admin scheduler settings were being ignored.
This issue was closed, with 2 commits, but the relevant one to this issue being ef225e0c04496d1be9b7b6f9ff8d42c34a8fdad9

The changes in this commit take the value of the `schedule_generate_every` setting for each cron group, but apply it incorrectly. The purpose of this setting is for the generating of schedules, and not for the scheduling of individual jobs.

For example, if the setting is 10, this means that every 10 minutes, the scheduler should generate entries in the `cron_schedule` table based on individual job settings, along with the `Schedule Ahead for` setting.

What's happening instead, is that the value entered is applied as an override for the minutes field in the cron expression for every job in the cron group - effectively making them all run at the same time. Worse, if the setting is 60 or more (i.e. infrequent schedule generation), then no jobs belonging to the group will ever be scheduled (as the minute value in a cron expression cannot be greater than 59).

**Steps To Reproduce**
1. Modify the `Generate Schedules Every` setting for the `default` cron group to be 60 (meaning schedules should be generated every 60 minutes.
2. Start cron service - notice that nothing is ever scheduled for the default group.

To properly respect the admin settings, a `last_generated_time` (or similar) value would need to be stored for each group, with the group only having schedules generated if the required amount of time had elapsed.
However, since this module is generating schedules for all jobs every hour, a simpler fix would be to just revert ef225e0c04496d1be9b7b6f9ff8d42c34a8fdad9

**Comment by whuber** [comment]
I can confirm this issue. I don't see any sense to overwrite the minute part of the cron expression with the config value of 'schedule_generate_every'. Can you fix this?

**Comment by gnuzealot** [comment]
I'm still not really clear what the value of the generate schedules every setting has, or the value of the groups really. By default the schedules are built 60 minutes out for all jobs in every group for every minute where a scheduled task is applicable for based on their schedule. Is there a use case where you'd need to see the schedule of jobs further into the future?

**Comment by aligent-lturner** [comment]
@gnuzealot I don't personally have such a use case, but I can't speak for others. The point is that a configuration setting is being used incorrectly, and causes jobs to be run at the wrong time (or not at all). If the setting is ignored because schedules are already being generated every hour, then that's fine.

**Comment by gnuzealot** [comment]
How does the frequency of the scheduling cause either of those issues? I don't see the distinction of generating a schedule for the next hour for anything that needs to to be scheduled for the next hour, or doing it every 15 minutes or any other increment.

**Comment by aligent-lturner** [comment]
It doesn't - that is what the setting is for (in core), but that is not how it is being used.
 
Instead, it is being used to override the minutes for each job's Cron expression, which is incorrect behaviour, and can lead to jobs not being run at all.

**Comment by aligent-lturner** [comment]
@gnuzealot this line specifically, https://github.com/magemojo/m2-ce-cron/blob/bb04585b05fbf0aa4e63294e59c67bef611a8f76/Model/Schedule.php#L256
This is setting the minutes part of the jobs schedule to be the groups "generate schedule override" value.
Jobs are already being scheduled regularly by the cron job, so there's really no reason to be using this value at all, but especially not in this (incorrect) way.

By way of an example, let's say I create a new cron group with 4 jobs in it:
1. Job_1, which I schedule as `0 * * * *`
1. Job_2, which I schedule as `15 * * * *`
1. Job_3, which I schedule as `30 * * * *`
1. Job_4, whcih I schedule as `45 * * * *`

Since I've only got jobs running every 15 minutes, I set the "generate schedules every" setting for the group to be 10 minutes, instead of the default 1.

Instead of having the 4 jobs running at 15 minute intervals, we end up with all 4 jobs running at 10 minutes past the hour.

**Comment by rhoerr** [comment]
Any word on this?

**Comment by dannocz** [comment]
I can confirm this bug is affecting the performance of the crons, since several jobs on our website should be scheduled every 15 minutes, but they are all scheduled at 15 minutes past the hour, so they have more work to do and they end up crashing or delaying each other significantly.

Furthermore, the indexes should be running once a minute. However, their schedule is also generated every 15 minutes, so this extension makes them run once per hour instead...
