### ISSUE TITLE
Is this module needed for Magento 2.3.x?

### ISSUE THREAD

**Issue by VincentMarmiesse** [magemojo/m2-ce-cron#68]
Hello,
Is this module still needed for Magento 2.3.x or did they fix the issues you're fixing with this module?

Thanks for your work!

**Comment by gnuzealot** [comment]
They don't seem to be all fixed, problems are still being reported. The additional functionality provided in the module also isn't in the base magento cron.

**Comment by VincentMarmiesse** [comment]
Thanks for your answer! Do you think it will work on a 2.3.1 out of the box?

**Comment by gnuzealot** [comment]
Yes, it's being used on 2.3x

**Comment by VincentMarmiesse** [comment]
Ok! Thanks again :+1:
