### ISSUE TITLE
Cron Execution table is always empty in admin panel

### ISSUE THREAD

**Issue by ytorbyk** [magemojo/m2-ce-cron#70]
Cron Execution table is always empty in admin panel when config:
**Stores -> Configuration -> Developer -> Template Settings -> Minify Html** set to _Yes_.
Looks like Magento template minification cannot handle properly the comment
> #Times are stored in UTC, converting to the locale timezone for report

That is how it looks
[](url)
<img width="1312" alt="Screen Shot 2019-06-12 at 12 12 02" src="https://user-images.githubusercontent.com/6418650/59338809-c291c300-8d0b-11e9-8360-816a5dbf66ce.png">

Tested on:
- Magento OS 2.3.1
- MageMojo_Cron 1.2.8

**Comment by duffner** [comment]
@gnuzealot, A simple change of the comment style to `//` or a PHP comment will address the issue.
