### ISSUE TITLE
Can't execute

### ISSUE THREAD

**Issue by buituanbg** [magemojo/m2-ce-cron#74]
When I click to Execute it got to error page 

There has been an error processing your request
Exception printing is disabled by default for security reasons.

Error log record number: 1154765993631

I saw in report 1154765993631 and this is error message:

> { 
> "0":"Area code is already set",
> "1":"
> 
> #1 Magento\\Framework\\App\\State\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#2 Magento\\Framework\\App\\State\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#3 Magento\\Framework\\App\\State\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/State\/Interceptor.php:26]\n#4 Magento\\Framework\\App\\State\\Interceptor->setAreaCode() called at [vendor\/magemojo\/m2-ce-cron\/Model\/Schedule.php:492]\n#5 MageMojo\\Cron\\Model\\Schedule->executeImmediate() called at [vendor\/magemojo\/m2-ce-cron\/Controller\/Adminhtml\/Reports\/Execute.php:32]\n#6 MageMojo\\Cron\\Controller\\Adminhtml\\Reports\\Execute->execute() called at [generated\/code\/MageMojo\/Cron\/Controller\/Adminhtml\/Reports\/Execute\/Interceptor.php:24]\n#7 MageMojo\\Cron\\Controller\\Adminhtml\\Reports\\Execute\\Interceptor->execute() called at [vendor\/magento\/framework\/App\/Action\/Action.php:108]\n#8 Magento\\Framework\\App\\Action\\Action->dispatch() called at [vendor\/magento\/module-backend\/App\/AbstractAction.php:231]\n#9 Magento\\Backend\\App\\AbstractAction->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#10 MageMojo\\Cron\\Controller\\Adminhtml\\Reports\\Execute\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#11 MageMojo\\Cron\\Controller\\Adminhtml\\Reports\\Execute\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/module-backend\/App\/Action\/Plugin\/Authentication.php:143]\n#12 Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#13 MageMojo\\Cron\\Controller\\Adminhtml\\Reports\\Execute\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#14 MageMojo\\Cron\\Controller\\Adminhtml\\Reports\\Execute\\Interceptor->___callPlugins() called at [generated\/code\/MageMojo\/Cron\/Controller\/Adminhtml\/Reports\/Execute\/Interceptor.php:39]\n#15 MageMojo\\Cron\\Controller\\Adminhtml\\Reports\\Execute\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/FrontController.php:159]\n#16 Magento\\Framework\\App\\FrontController->processRequest() called at [vendor\/magento\/framework\/App\/FrontController.php:99]\n#17 Magento\\Framework\\App\\FrontController->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#18 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#19 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [app\/code\/Ess\/M2ePro\/Plugin\/HealthStatus\/Magento\/Framework\/App\/FrontController.php:79]\n#20 Ess\\M2ePro\\Plugin\\HealthStatus\\Magento\\Framework\\App\\FrontController->processDispatch() called at [app\/code\/Ess\/M2ePro\/Plugin\/AbstractPlugin.php:43]\n#21 Ess\\M2ePro\\Plugin\\AbstractPlugin->execute() called at [app\/code\/Ess\/M2ePro\/Plugin\/HealthStatus\/Magento\/Framework\/App\/FrontController.php:42]\n#22 Ess\\M2ePro\\Plugin\\HealthStatus\\Magento\\Framework\\App\\FrontController->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#23 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#24 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:26]\n#25 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/Http.php:136]\n#26 Magento\\Framework\\App\\Http->launch() called at [generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php:24]\n#27 Magento\\Framework\\App\\Http\\Interceptor->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:258]\n#28 Magento\\Framework\\App\\Bootstrap->run() called at [pub\/index.php:40]\n<\/pre>",
>    "url":"\/magemojocron\/reports\/execute\/jobcode\/sales_grid_order_creditmemo_async_insert\/key\/60c251d5681a53088e0ae300163841241baaeca9c7822bf0eebba1f216468ac5\/",
>    "script_name":"\/index.php"
> }

**Comment by cdbessig** [comment]
Same here.

**Comment by gnuzealot** [comment]
Issue was fixed in https://github.com/magemojo/m2-ce-cron/commit/01ed9d91b8a6a2d78c220381dad05997fa657d40#diff-16f39d85ba47492ad0b58a52ae4c2a41
