### ISSUE TITLE
Cleanup does not include cron.pid

### ISSUE THREAD

**Issue by bobbrodie** [magemojo/m2-ce-cron#75]
When the module runs **initialize()**, it does this:
```
$this->setPid('cron.pid',$pid);
```
The following is then called:
```
public function setPid($file,$scheduleid) {
  #print 'file='.$file;
  file_put_contents(self::VAR_FOLDER_PATH.'/cron/'.$file,$scheduleid);
}
```
At this point, we have a file of `var/cron/cron.pid` with the PID in it.

Later, there is a function called **cleanupProcesses()**:
```
public function cleanupProcesses() {
  $running = array();
  $pids =  $this->getRunningPids();
  foreach ($pids as $pid=>$scheduleid) {
    if (!$this->checkProcess($pid)) {
      $this->unsetPid('cron.'.$pid);
      $this->resource->resetSchedule();
    } else {
      array_push($running,$pid);
    }
  }
  $this->runningPids = $running;
}
```

This runs **getRunningPids()**:
```
public function getRunningPids() {
  $pids = array();
  $filelist = scandir(self::VAR_FOLDER_PATH.'/cron/');

  foreach ($filelist as $file) {
    if ($file != 'cron.pid') {
      $pid = str_replace('cron.','',$file);
      if (is_numeric($pid)) {
        $pids[$pid] = file_get_contents(self::VAR_FOLDER_PATH.'/cron/'.$file);
      }
    }
  }
  return $pids;
}
```

While the `$pids` array is being built, the `cron.pid` file is skipped:
```
public function unsetPid($pid) {
  $pidfile = self::VAR_FOLDER_PATH.'/cron/'.$pid;
  if(file_exists($pidfile)) {
    unlink($pidfile);
  }
}
```

This leaves the `cron.pid` file on the server indefinitely. Is there a reason for this?

**Comment by gnuzealot** [comment]
This is by design and necessary for the cron to function, the pid is for the php process that runs the service, this file should always exist.

**Comment by bobbrodie** [comment]
@gnuzealot so the file should never receive a new PID, and should just remain as it was created indefinitely?

**Comment by bobbrodie** [comment]
@gnuzealot can you confirm that if **cron.pid** disappears for any reason, that the cron server on your end that we don't have access to would not spin up any additional processes, causing there to be duplicates?
