### ISSUE TITLE
Issue with Wyomind Cronscheduler

### ISSUE THREAD

**Issue by vinothkumarblaze** [magemojo/m2-ce-cron#76]
i am gettign this error in log file , my catalog price rule reset on mid-night.
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Magento\Cron\Observer\ProcessCronQueueObserver::__construct(), 11 passed in /home/srikoreka/releases/20190716070528/vendor/wyomind/cronscheduler/Plugin/Cron/Observer/ProcessCronQueueObserver.php on line 72 and exactly 13 expected in /home/srikoreka/releases/20190716070528/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php:161

**Comment by gnuzealot** [comment]
These modules are unfortunately incompatible with each other.
