### ISSUE TITLE
Error in messages field.

### ISSUE THREAD

**Issue by adamrandazzo** [magemojo/m2-ce-cron#82]
I just installed the extension and it's working much better than the standard cron, with the exception of one of the groups. The error below is showing up in the `cron_schedule` `messages` field for the `consumers_runner` job code. Any ideas?

Thanks! 

```In Config.php line 41:
                                                
  Consumer 'consumers_runner' is not declared.  
                                                

queue:consumers:start [--max-messages MAX-MESSAGES] [--batch-size BATCH-SIZE] [--area-code AREA-CODE] [--single-thread] [--pid-file-path PID-FILE-PATH] [--] <consumer>```

**Comment by gnuzealot** [comment]
@adamrandazzo what magento version are you getting this on?

**Comment by gnuzealot** [comment]
The latest version of the cron module is not compatible with magento versions prior to 2.3. Use the 1.2 version of the module, instructions are in the readme.
