### ISSUE TITLE
DI compile error on Magento 2.2.11

### ISSUE THREAD

**Issue by andrey-bondarenko** [magemojo/m2-ce-cron#84]
We have updated our store to Magento 2.2.11 and I got this error

  Class Magento\MessageQueue\Model\Cron\ConsumersRunner does not exist  

You use this class in https://github.com/magemojo/m2-ce-cron/blob/master/Model/Schedule.php
But in Magento 2.2.11 this module doesn't exist

**Comment by michelve** [comment]
same issue on my end.

error when compiling magento

**Comment by gnuzealot** [comment]
The latest version of the cron module is not compatible with magento versions prior to 2.3. Use the 1.2 version of the module, instructions are in the readme.

**Comment by michelve** [comment]
thank you
