### ISSUE TITLE
RabbtiMQ connection_closed_abruptly

### ISSUE THREAD

**Issue by ytorbyk** [magemojo/m2-ce-cron#86]
Hi team,

Extension version 1.3.1
Magento version 2.3.3

Since consumers are running with` timeout -s 9 30 ` we have WARNING REPORT about connection_closed_abruptly each minute.

Can you help to understand if it's expected behavior or what should be changed in order to fix it?
Probably some RabbitMQ settings?
Since currently, the queues work incorrectly and sometimes we lose messages.

Thanks,
Yurii

**Comment by gnuzealot** [comment]
This behavior is by design. Those run out of the consumers crons can run in infinite loops so the timeout was implemented. That timeout is adjustable in the admin.

**Comment by ytorbyk** [comment]
@gnuzealot, thanks for the response.  

If the behavior is by design then is it okay if some messages cannot be completed successfully?
We've noticed that some events disappeared from the RabbitMQ queue (looks like their processing was stated), but consumer task wasn't complete or completed partially.
Is the behavior expected too?

**Comment by gnuzealot** [comment]
This is expected behavior of the cron module, not of the rabbitmq queue. This code is a mitigation of a larger bug inherit to M2 consumers.
