### ISSUE TITLE
Command "queue:consumers:start" is not defined.

### ISSUE THREAD

**Issue by mlambley** [magemojo/m2-ce-cron#89]
I'm getting a lot of noise in the stdout of `bin/magento cron:run`

```
Healthchecking Cron Service
Starting Service

  Command "queue:consumers:start" is not defined.

  Did you mean one of these?
      ce_mq:consumers:start
      queue:consumers:list

  Command "queue:consumers:start" is not defined.

  Did you mean one of these?
      ce_mq:consumers:start
      queue:consumers:list
```
...etc

I'm running `1.3.1-stable` on Magento 2.3.4. Is this supposed to happen?

**Comment by conradreisch** [comment]
Hi mlambley, I'm having the same issue. Also "bulk actions" are not properly performed by cron. Did you find a way to fix this?

**Comment by mlambley** [comment]
No unfortunately not.

**Comment by conradreisch** [comment]
Hi Mark,
maybe I have a solution.
I also saw messages like 'Consumer “async.operations.all” skipped as required connection “amqp” is not configured. Unknown connection name amqp' in the debug.log which lead me to the following articles:
- https://magento.stackexchange.com/questions/269928/consumer-async-operations-all-skipped-as-required-connection-amqp-is-not-con
- https://community.magento.com/t5/Magento-2-x-Technical-Issues/Magento-2-3-3-update-product-attributes-in-bulk-does-not-work/td-p/294215

After adding the following information to my env.php, the error messages seem to be gone. Also the bulk update is working again.

```
'cron_consumers_runner' => [
        'cron_run' => true,
        'max_messages' => 2000,
        'consumers' => [
            'product_action_attribute.update',
	    'product_action_attribute.website.update',
	    'codegeneratorProcessor',
	    'exportProcessor',
	    'quoteItemCleaner',
	    'inventoryQtyCounter',
	    'codegeneratorProcessor'
        ]
]
```

It sure fixed the problem for me. Hopefully, its also helping you.
BR, Conrad

**Comment by mlambley** [comment]
Ok I can confirm that this is a Magento issue, not a m2-ce-cron issue, thanks for that buddy.

**Comment by DylanHopman** [comment]
Hi,

Thanks for your quick reply. Unfortunately it doesn't solve the problem :(
